export const callStates = {
  CALL_UNAVAILABLE: 'CALL_UNAVAILABLE',
  CALL_AVAILABLE: 'CALL_AVAILABLE',
  CALL_REQUESTED: 'CALL_REQUESTED',
  CALL_IN_PROGRESS: 'CALL_IN_PROGRESS'
};

export const SET_LOCAL_STREAM = 'SET_LOCAL_STREAM';
export const SET_CALL_STATE = 'SET_CALL_STATE';
export const SET_CALLING_DIALOG_VISIBLE = 'SET_CALLING_DIALOG_VISIBLE';
export const SET_CALLER_USERNAME = 'SET_CALLER_USERNAME';
export const SET_CALL_REJECTED = 'SET_CALL_REJECTED';
export const SET_REMOTE_STREAM = 'SET_REMOTE_STREAM';
export const SET_LOCAL_MICROPHONE_ENABLED = 'SET_LOCAL_MICROPHONE_ENABLED';
export const SET_LOCAL_CAMERA_ENABLED = 'SET_LOCAL_CAMERA_ENABLED';
export const SET_SCREEN_SHARING_ACTIVE = 'SET_SCREEN_SHARING_ACTIVE';
export const RESET_CALL_STATE = 'RESET_CALL_STATE';
export const SET_GROUP_CALL_ACTIVE = 'CALL_SET_GROUP_CALL_ACTIVE';
export const SET_GROUP_CALL_STREAMS = 'SET_GROUP_CALL_STREAMS';
export const CLEAR_GROUP_CALL_DATA = 'CLEAR_GROUP_CALL_DATA';
export const SET_CHAT_MESSAGE = 'SET_CHAT_MESSAGE';